### PR TITLE
Upgrade Nuget references and add new Web API specific enrichers and 

### PR DESCRIPTION
**Pull request by tsimbalar**
I got a bit carried away, and this PR contains a bit more than initially planned ... I can try and split it in several PRs if you think it's better ...

This PR contains : 
- upgrade of the whole project to later versions of *SerilogWeb.Classic* (v3.0.20) ... which therefore upgrades the *Serilog* reference to v2.5. 
After this upgrade, generating the nuget package produces something like this : 
image
This means that the **Major version number of this package should be incremented too** (to *v2.0*)

- several enrichers in the namespace `SerilogWeb.Classic.WebApi.Enrichers` built specifically to capture some *Web API* specific information : 
  - `WebApiActionNameEnricher`
  - `WebApiControllerNameEnricher`
  - `WebApiRouteDataEnricher`
  - `WebApiRouteTemplateEnricher` (this is actually the one I was trying to do as for datalust/seq-releases#622 , but I thought I might as well do the other ones too ...)

A configuration like this : 

```csharp
Log.Logger = new LoggerConfiguration()
    .Enrich.With<WebApiRouteTemplateEnricher>()
    .Enrich.With<WebApiControllerNameEnricher>()
    .Enrich.With<WebApiRouteDataEnricher>()
    .Enrich.With<WebApiActionNameEnricher>()
    .WriteTo.Trace(new JsonFormatter())
    .CreateLogger();
```

in a Web API app with a controller like this one : 
```csharp
public class ValuesController : ApiController
{
    // GET api/values
    public IEnumerable<string> Get()
    {
        return new string[] { "value1", "value2" };
    }

    [Route("api/values/shouldthrowexception")]
    [HttpGet]
    public string ShouldThrowException()
    {
        throw new SyntheticException(nameof(ShouldThrowException));
    }

    // GET api/values/5
    public string Get(int id)
    {
        return "value";
    }
}
```

generates events like those in the Trace output when accessing `/api/values`, `api/values/6` or `/api/values/shouldthrowexception`: 
```json
{
	"Timestamp": "2017-10-26T21:58:52.6501081+02:00",
	"Level": "Information",
	"MessageTemplate": "HTTP {Method} {RawUrl} responded {StatusCode} in {ElapsedMilliseconds}ms",
	"Properties": {
		"Method": "GET",
		"RawUrl": "/api/values/",
		"StatusCode": 200,
		"ElapsedMilliseconds": 6,
		"SourceContext": "SerilogWeb.Classic.ApplicationLifecycleModule",
		"WebApiRouteTemplate": "api/{controller}/{id}",
		"WebApiController": "Values",
		"WebApiRouteData": {
			"controller": "values"
		},
		"WebApiAction": "Get"
	}
}
```
```json
{
	"Timestamp": "2017-10-26T21:59:21.3880735+02:00",
	"Level": "Information",
	"MessageTemplate": "HTTP {Method} {RawUrl} responded {StatusCode} in {ElapsedMilliseconds}ms",
	"Properties": {
		"Method": "GET",
		"RawUrl": "/api/values/6",
		"StatusCode": 200,
		"ElapsedMilliseconds": 2,
		"SourceContext": "SerilogWeb.Classic.ApplicationLifecycleModule",
		"WebApiRouteTemplate": "api/{controller}/{id}",
		"WebApiController": "Values",
		"WebApiRouteData": {
			"controller": "values",
			"id": "6"
		},
		"WebApiAction": "Get"
	}
}
```
```json
{
	"Timestamp": "2017-10-26T21:59:52.8379675+02:00",
	"Level": "Error",
	"MessageTemplate": "HTTP {Method} {RawUrl} responded {StatusCode} in {ElapsedMilliseconds}ms",
	"Exception": "SerilogWeb.Classic.WebApi.Test.SyntheticException: ShouldThrowException\r\n... snip ...",
	"Properties": {
		"Method": "GET",
		"RawUrl": "/api/values/shouldthrowexception",
		"StatusCode": 500,
		"ElapsedMilliseconds": 2512,
		"SourceContext": "SerilogWeb.Classic.ApplicationLifecycleModule",
		"WebApiRouteTemplate": "api/values/shouldthrowexception",
		"WebApiController": "Values",
		"WebApiRouteData": {},
		"WebApiAction": "ShouldThrowException"
	}
}

```

In order to do that, the library automatically injects an `ActionFilter` in the Web API pipeline : `StoreWebApiInfoInHttpContextActionFilter`. That action filter stores some of the `ActionContext` in `HttpContext.Current` to make them available to the enrichers.

Obviously, because it relies on `HttpContext`, this cannot work in *self-hosted* scenarios, but I believe this was already expected.

I believe those would be some rather useful enricher (at least for me :p ) , and I would love some feedback, mostly I have doubts about : 
- is it ok to add stuff to `HttpContext.Current` ? is there a cleaner way that would be more `Web APish` , but still allow the *enriched* data to be captures by the `SerilogWeb.Classic` module ? 
- are the names and namespaces good enough ?
- are the default names under which those properties are stored intuitive enough ?
- are there some edge cases I might have missed ? 

Thanks in advance !

### CODE REVIEW

**Comment by nblumhardt** [comment]
Very nice! Will sort out the major version and push this through.

**Comment by tsimbalar** [comment]
@nblumhardt Any chance you can publish a new version of this one (with an increased major version number) ? I know the *SerilogWeb* projects have a bit of a lower priority, so if I can help, I'd be happy to :) 

Also I'd like to do something similar for ASP.NET MVC (not Core) .... would it be possible to create a new repo in this organization. The repo's name could be something like `classic-mvc` and the correspounding Nuget package could be `SerilogWeb.Classic.Mvc` ? and I could take it from there to prepare a first version :)

Thanks in advance 🙇

**Comment by nblumhardt** [comment]
Looks like the CI webhooks aren't firing - I probably need to re-authorize GitHub. I'll hit the manual build button and see what happens :-)

**Comment by nblumhardt** [comment]
> The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to find 'C:\projects\classic-webapi\src\SerilogWeb.Classic.WebApi\bin\Release\SerilogWeb.Classic.WebApi.dll'. Make sure the project has been built.

Hmm....

**Comment by nblumhardt** [comment]
https://github.com/serilog-web/classic-mvc created, you should have admin access there, let me know if you need a hand.

I've added it to AppVeyor, build status badge is:

```
[![Build status](https://ci.appveyor.com/api/projects/status/3yidmjq6pm0f2pii?svg=true)](https://ci.appveyor.com/project/serilog-web/classic-mvc)
```

It'll need an _appveyor.yml_ file to do anything interesting :-)

I'm not sure what the story with the build in this repository is - please feel free to jump in, and let me know if the CI problem still needs some action from me 👍 

Cheers!

**Comment by tsimbalar** [comment]
Great, thanks a lot ! I'll start to get it started soon 👍

**Pull request merged**
